name: CI Pipeline for Stock Price Prediction Model

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas scikit-learn pylint pytest

      # Step 4: Run Linting
      - name: Run pylint
        run: |
          pylint src tests --disable=C0304,C0305 --fail-under=9.5

      # Step 5: Run Tests
      - name: Run Tests
        env:
          PYTHONPATH: ./src
        run: pytest
