name: CI Pipeline for Stock Price Prediction Model

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Pull DVC data (Local Setup)
      - name: Pull DVC data
        run: dvc pull

      # Step 5: Run Linting
      - name: Run Linting
        run: |
          pylint src tests --fail-under=9.5

      # Step 6: Run Tests
      - name: Run Tests
        env:
          PYTHONPATH: ./src
        run: pytest

      # Step 7: Visualize DVC Pipeline (Optional)
      - name: Visualize DVC Pipeline
        run: dvc dag --dot | dot -Tpng -o pipeline.png

      # Step 8: Save DVC Pipeline Visualization (Optional)
      - name: Save Pipeline Visualization
        uses: actions/upload-artifact@v3
        with:
          name: dvc-pipeline
          path: pipeline.png